app/domains/forms.py
# app/domains/forms.py
# This file is part of veximpy

from os import path
from flask_wtf import FlaskForm
from wtforms import BooleanField, IntegerField, PasswordField, SelectField, StringField, SubmitField
from wtforms_components import read_only
from wtforms.validators import DataRequired, EqualTo, IPAddress, Length, NumberRange, Optional
from ..lib.forms_fields import TextAreaSepListField
from ..lib.forms_validators import IPList, PasswordRules, MX, DomainExists, QuotaDomains
from ..config.settings import domaindefaults, settings

class DomainFormLocal(FlaskForm):
    """
    Form for add/edit domains
    """

    def __init__(self, obj=None, action='add', *args, **kwargs):
        super().__init__(obj=obj)
        self.action = action.lower()
        if action.lower() == 'add':
            del self.submitedit
        elif action.lower() == 'edit':
            del self.password1
            del self.password2
            del self.submitadd
            read_only(self.domain)
            self.domain.validators = []
            read_only(self.maildir)
            self.maildir.description = ''
            self.maildir.validators = []
            self.pwdcharallowed = self.pwd_charallowed.data

    def domain_save(self, domain):
        if self.action == 'add':
            self.password1.flags.required = True
        if self.validate_on_submit():
            is_mailinglist = 0
            self.populate_obj(domain)
            domain.maildir = path.join(self.maildir.data, self.domain.data)
            domain.blocklists = 0
            domain.mailinglists = is_mailinglist
            domain.type = 'local'
            return True
        return False

    action = 'add'
    pwdcharallowed = settings['PWDCHARSALLOWED']
    pwdlengthmin = settings['PWDLENGTHMIN']

    enabled = BooleanField('Enabled', false_values={0, False, 'false', ''})
    domain = StringField('Domain', validators=[Length(min=3, max=255), MX, DomainExists])
    comment = StringField('Comment', validators=[Optional(), Length(min=0, max=255)])
    maildir = StringField('Maildir base path. Domain name will be appended.', description='You can <b>not</b> change this later.', validators=[Length(min=3, max=4096)])
    password1 = PasswordField('Password for postmaster account', validators=[PasswordRules, EqualTo('password2', message='Password does not match confirmation password.')])
    password2 = PasswordField('Confirm Password')
    uid = IntegerField('System UID', validators=[NumberRange(min=99, max=65535)])
    gid = IntegerField('System GID', validators=[NumberRange(min=99, max=65535)])
    max_accounts = IntegerField('Max. Accounts', validators=[NumberRange(min=1, max=2147483647)])
    quotas = IntegerField('Default quota for each account [MB]. 0 means unlimited', validators=[QuotaDomains, NumberRange(min=0, max=2147483647)])
    quotasmax = IntegerField('Max. quota for each account [MB]. 0 means unlimited', validators=[QuotaDomains, NumberRange(min=0, max=2147483647)])
    maxmsgsize = IntegerField('Max. message size [kB]', description='The maximum size for incoming mail (user tunable)', validators=[NumberRange(min=1000, max=2147483647)])
    #type = StringField('Domain type', validators=[DataRequired(), Length(min=1, max=5)])
    avscan = BooleanField('Anti virus scan', description='Run anti virus scan on mails.', false_values={0, False, 'false', ''})
    spamassassin = BooleanField('Spam check', description='Run spamassassin on mails.', false_values={0, False, 'false', ''})
    sa_tag = IntegerField('Tag spam above this score', description='Above this score the "X-Spam-Flag: YES" header will be added.', validators=[NumberRange(min=0, max=99)])
    sa_refuse = IntegerField('Refuse spam above this score', validators=[NumberRange(min=0, max=99)])
    #blocklists = 
    #mailinglists = 
    pipe = BooleanField('Allow piping mails to programs', false_values={0, False, 'false', ''})
    out_ip = TextAreaSepListField('Outgoing IPs. List of IPv4/IPv6 addresses. One per line.', validators=[Length(min=0, max=255), IPList], separator=' ; ', render_kw={"rows": 5, "cols": 255})
    host_smtp = StringField('SMTP host', validators=[DataRequired(), Length(min=2, max=64)])
    host_imap = StringField('IMAP host', validators=[DataRequired(), Length(min=2, max=64)])
    host_pop = StringField('POP3 host', validators=[DataRequired(), Length(min=2, max=64)])
    relayto = StringField('Relay mails to IP', validators=[Optional(), IPAddress(ipv4=True, ipv6=True)])
    pwd_charallowed = StringField('Allowed password characters', validators=[Length(min=64, max=255)])
    pwd_lengthmin = IntegerField('Minimum length for passwords', validators=[NumberRange(min=domaindefaults['pwd_lengthmin'], max=2147483647)])
    #pwd_rules

    submitadd = SubmitField('Add domain')
    submitedit = SubmitField('Save domain')
    submitcancel = SubmitField('Cancel')

class DomainFormAlias(FlaskForm):

    def __init__(self, obj=None, action='add',  **kwargs):
        super().__init__(obj=obj)
        if action.lower() == 'add':
            del self.submitedit
        elif action.lower() == 'edit':
            del self.submitadd
            read_only(self.alias)
            self.alias.validators = []

    def domain_save(self, domain):
        if self.validate_on_submit():
            is_mailinglist = 0
            self.populate_obj(domain)
            domain.blocklists = 0
            domain.mailinglists = is_mailinglist
            domain.type = 'alias'
            return True
        return False

    enabled = BooleanField('Enabled', false_values={0, False, 'false', ''})
    alias = StringField('Domain', validators=[Length(min=3, max=255), MX, DomainExists])
    domain_id = SelectField('Redirect mails to', coerce=int)
    host_smtp = StringField('SMTP host', validators=[DataRequired(), Length(min=2, max=64)])
    host_imap = StringField('IMAP host', validators=[DataRequired(), Length(min=2, max=64)])
    host_pop = StringField('POP3 host', validators=[DataRequired(), Length(min=2, max=64)])
    submitadd = SubmitField('Add domain')
    submitedit = SubmitField('Save domain')
    submitcancel = SubmitField('Cancel')
   
class DomainFormRelay(FlaskForm):

    def __init__(self, obj=None, action='add',  **kwargs):
        super().__init__(obj=obj)
        if action.lower() == 'add':
            del self.submitedit
        elif action.lower() == 'edit':
            del self.submitadd
            read_only(self.domain)
            self.domain.validators = []

    def domain_save(self, domain):
        if self.validate_on_submit():
            is_mailinglist = 0
            self.populate_obj(domain)
            domain.blocklists = 0
            domain.mailinglists = is_mailinglist
            domain.type = 'relay'
            return True
        return False

    enabled = BooleanField('Enabled', false_values={0, False, 'false', ''})
    domain = StringField('Domain', validators=[Length(min=3, max=255), MX, DomainExists])
    submitadd = SubmitField('Add domain')
    submitedit = SubmitField('Save domain')
    submitcancel = SubmitField('Cancel')

class DomainFormMailinglist(FlaskForm):
    pass

app/domains/__init__.py
# app/domains/__init__.py
# This file is part of veximpy

from flask import Blueprint

domains = Blueprint('domains', __name__, template_folder='templates/domains')

from . import views

app/domains/views.py
# app/domains/views.py
# This file is part of veximpy

import logging
from flask import flash, redirect, render_template, request, url_for
from flask_login import login_required
from flask_wtf.csrf import generate_csrf
from sqlalchemy.orm.exc import NoResultFound
#from wtforms.validators import DataRequired
#from wtforms_alchemy import model_form_factory
#from werkzeug import MultiDict
from markupsafe import Markup
from .forms import DomainFormLocal, DomainFormAlias, DomainFormRelay, DomainFormMailinglist
from ..accounts.forms import AccountFormLocal
from . import domains
from ..models.models import Domain, Domainalia, User
from ..app import db
from ..config.settings import domaindefaults, aliasdomaindefaults, domainlist_title
from ..lib.decorators import domainid_check, domaintyp_required, siteadmin_required

@domains.route('/domainlist/<domaintype>/')
@domains.route('/domainlist/', defaults={'domaintype': 'local'})
@login_required
@siteadmin_required
@domaintyp_required
def domainlist(domaintype):
    """
    Render the homepage template on the /domains_alias route
    """

    if domaintype == 'alias':
        domainlist = Domainalia.query.order_by(Domainalia.alias).all()
    else:
        domainlist = Domain.query.filter(Domain.type == domaintype).order_by(Domain.domain)

    return render_template('domains/domainlist.html',
        title="Domains", list_title=domainlist_title[domaintype] + " Domains",
        domainlist=domainlist,
        domaintype=domaintype)

@domains.route('/domains_enabled/<int:domainid>/<domaintype>/', methods=['GET', 'POST'])
@domains.route('/domains_enabled/', defaults={'domainid': 0, 'domaintype': 'local'}, methods=['GET', 'POST'])
@login_required
@siteadmin_required
@domainid_check
def domains_enabled(domainid, domaintype):
    """
    Render the homepage template on the / route
    """

    try:
        if domaintype == 'alias':
            domain = Domainalia.query.filter(Domainalia.domainalias_id == domainid).one()
        else:
            domain = Domain.query.filter(Domain.domain_id == domainid).one()
    except NoResultFound:
        flash(Markup('We couldn\'t find the domainid <b>' + str(domainid) + '</b>.'), 'error')
        return redirect(url_for('domains.domainlist', domaintype='local'))

    if domain.is_sitedomain or domain.enabled == 0:
       domain.enabled = 1
       enabledtxt = 'enabled'
       flashtype = 'success'
    else:
        domain.enabled = 0
        enabledtxt = 'disabled'
        flashtype = 'warning'
    db.session.commit()
    flash(Markup('You have successfully ' + enabledtxt +' the domain <b>' + domain.domainname + '</b>.'), flashtype)

    return redirect(url_for('domains.domainlist', _anchor=domainid, domaintype=domaintype))

@domains.route('/domains_add/<domaintype>', methods=['GET', 'POST'])
@domains.route('/domains_add/', defaults={'domaintype': 'local'}, methods=['GET', 'POST'])
@login_required
@siteadmin_required
@domaintyp_required
def domains_add(domaintype):
    """
    Render the homepage template on the / route
    """

    add_domain = True

    if domaintype == 'local':
        form = DomainFormLocal(obj=Domain(**domaindefaults), action='add')
        #form.process(**domaindefaults)
    elif domaintype == 'alias':
        domain_id_available = (Domain.query.with_entities(Domain.domain_id, Domain.domain).filter(Domain.domain_id>1)).filter(Domain.type == 'local').order_by(Domain.domain).all()
        domain_id_list = [(_.domain_id, _.domain) for _ in domain_id_available]
        form = DomainFormAlias(obj=Domainalia(**aliasdomaindefaults), action='add')
        form.domain_id.choices = domain_id_list
        #form.process(**aliasdomaindefaults)
    elif domaintype == 'relay':
        form = DomainFormRelay(obj=Domain(**domaindefaults), action='add')
        #form.process(**domaindefaults)
    elif domaintype == 'list':
        form = DomainFormMailinglist(obj=Domain(**domaindefaults), action='add')
        #form.process(**domaindefaults)


#    if form and request.method == 'GET':
#        form.process(MultiDict(domaindefaults))

    if form.submitcancel.data:
        return redirect(url_for('domains.domainlist', domaintype=domaintype))

    if request.method == 'POST':
        domainname = ''
        if domaintype == 'alias':
            domainname = form.alias.data
            domain = Domainalia()
        else:
            domainname = form.domain.data
            domain = Domain()

        #        elif domaintype == 'list':
        #            is_mailinglist = 1
        #            form = DomainFormMailinglist()

        if form.domain_save(domain):
            try:
                # add domain to the database
                db.session.add(domain)
                db.session.commit()
            except:
                # in case domain name already exists
                db.session.rollback()
                flash(Markup('Domain <b>' + domainname + '</b> already exists.'), 'error')
                return render_template('domains/domain.html', action='Add',
                                    domainname = '', 
                                    add_domain=add_domain, form=form,
                                    title='Add ' + domaintype + ' Domain')
            
            if domaintype == 'local':
                # add postmaster account
                account = User(**domain.get_postmasterdefaults_dict())
                form_account = AccountFormLocal(obj=account, action='addPostmaster', domain=domain)
                print(account.__dict__)
                form_account.process(**{**domain.get_postmasterdefaults_dict(), 'password1': form.password1.data, 'csrf_token': generate_csrf()})
                #form_account.password1.data = form.password1.data
                #form_account.password2.data = form.password2.data
                if form_account.account_save(account):
                    try:
                        db.session.add(account)
                        db.session.commit()
                    except:
                        db.session.rollback()
                        flash(Markup('Postmaster account for <b>' + domainname + '</b> name already exists.'), 'error')
                        return render_template('domains/domain.html', action='Add',
                                            domainname = '', 
                                            add_domain=add_domain, form=form,
                                            title='Add ' + domaintype + ' Domain')
                else:
                    logging.debug(form_account.errors)
                    flash(Markup('An error occured on adding a postmaster account to domain <b>' + domainname + '</b> during form data validation.'), 'error')
                    return render_template('domains/domain.html', action='Add',
                                            domainname = '', 
                                            add_domain=add_domain, form=form,
                                            title='Add ' + domaintype + ' Domain')

#                    return render_template('accounts/account.html', action='Add',
#                                    accountname = '', 
#                                    add_account=True, form=AccountFormLocal(obj=account, action='add', domain=domain),
#                                    domainname=domain.domain,
#                                    domainid=domain.id, 
#                                    title='Add ' + 'local' + ' account')





            flash(Markup('You have successfully added the domain <b>' + domainname + '</b>'), 'success')

            # redirect to domainlist page
            return redirect(url_for('domains.domainlist', _anchor=domain.id, domaintype=domaintype))
        else:
            flash(Markup('An error occured on adding domain <b>' + domainname + '</b> during form data validation.'), 'error')

    # load domain template
    return render_template('domains/domain.html', action='Add',
                            domainname = '', 
                            add_domain=add_domain, form=form,
                            title='Add ' + domaintype + ' domain')

@domains.route('/domains_edit/<int:domainid>/<domaintype>/', methods=['GET', 'POST'])
#@domains.route('/domains_edit/', defaults={'domainid': 0, 'domaintype': 'local'}, methods=['GET', 'POST'])
@login_required
@siteadmin_required
@domaintyp_required
@domainid_check
def domains_edit(domainid, domaintype):
    """
    Render the homepage template on the / route
    """

    add_domain = False

    # create DB object for domain
    try:
        if domaintype == 'alias':
            domain = Domainalia.query.filter_by(domainalias_id=domainid).one()
        else:
            domain = Domain.query.filter_by(domain_id=domainid).one()
        domainname = domain.domainname
    except NoResultFound:
        flash(Markup('We couldn\'t find the domainid <b>' + str(domainid) + '</b>.'), 'error')
        return redirect(url_for('domains.domainlist', domaintype='local'))

    # create forms
    if domaintype == 'local':
        form = DomainFormLocal(obj=domain, action='edit')
    elif domaintype == 'alias':
        form = DomainFormAlias(obj=domain, action='edit')
        form.domain_id.choices = Domain.query.with_entities(Domain.domain_id, Domain.domain).filter(Domain.domain_id>1, Domain.domain!=domain.alias, Domain.type == 'local').order_by(Domain.domain).all()
    elif domaintype == 'relay':
        form = DomainFormRelay(obj=domain, action='edit')
    elif domaintype == 'list':
        form = DomainFormMailinglist(obj=domain, action='edit')

    if form.submitcancel.data:
        return redirect(url_for('domains.domainlist', _anchor=domainid, domaintype=domaintype))

    if request.method == 'POST':
        if form.domain_save(domain):
            try:
                db.session.commit()
                flash(Markup('You have successfully edited the domain <b>' + domainname + '</b>'), 'success')

app/templates/domains/domain.html
<!-- app/templates/domains/domain.html -->
<!-- This file is part of veximpy -->

{% import "bootstrap/wtf.html" as wtf %}
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}
    {% if add_domain %}
        Add Domain
    {% else %}
        Edit Domain
    {% endif %}
{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center">
            {% if add_domain %}
                <h1>{{ title }}</h1>
            {% else %}
                <h1>{{ title }} <b>{{ domainname }}</b></h1>
            {% endif %}
            <br/>
            {{ wtf.quick_form(form) }}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/domains/domainlist.html
<!-- app/templates/domainlist.html -->
<!-- This file is part of veximpy -->

{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Domains{% endblock %}
{% block body %}
<script class="init" type="text/javascript">
    $(document).ready(function() {
         $('#localtable').DataTable( {
              "columnDefs": [
                  { "orderable": false, "targets": [ 6, 7, 8 ] }
              ]
         } );
         $('#aliastable').DataTable( {
              "columnDefs": [
                  { "orderable": false, "targets": [ 2, 3, 4 ] }
              ]
         } );
         $('#relaytable').DataTable( {
              "columnDefs": [
                  { "orderable": false, "targets": [ 1, 2, 3 ] }
              ]
         } );
    } );
</script>
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <h1 style="text-align:center;">{{ list_title }}</h1>
        {% if domainlist %}
          <hr class="intro-divider">
          <div class="postition-absolute" style="text-align: center">
            <a href="{{ url_for('domains.domains_add', domaintype=domaintype) }}" class="btn btn-default">
              <i class="fa fa-plus"></i>
              Add Domain
            </a>
          </div>
          <div class="center table-responsive-sm">
            <table id="{{ domaintype }}table" class="table table-sm table-striped table-bordered table-hover rotate-75">
                <caption>List of domains</caption>
                <colgroup>
                    <col span="1" style="width: *;">
                    {% if domaintype=='alias' %}
                      <col span="1" style="width: *;">
                    {% endif %}
                    {% if domaintype=='local' %}
                      <col span="1" style="width: *;">
                      <col span="1" style="width: 100px;">
                      <col span="1" style="width: 100px;">
                      <col span="1" style="width: 40px;">
                      <col span="1" style="width: 40px;">
                    {% endif %}
                    <col span="1" style="width: 35px;">
                    <col span="1" style="width: 35px;">
                    <col span="1" style="width: 35px;">
                </colgroup>
              <thead>
                <tr class="rotate-75">
                  <th class="rotate-75"><div><span>Domainname</span></div></th>
                  <!-- <th width="30%"> Maildir </th> -->
                  {% if domaintype=='alias' %}
                    <th class="rotate-75"><div><span>Alias for</span></div></th>
                  {% endif %}
                  {% if domaintype=='local' %}
                    <th class="rotate-75"><div><span>Relay to</span></div></th>
                    <th class="rotate-75"><div><span>Local Accounts</span></div></th>
                    <th class="rotate-75"><div><span>Alias Accounts</span></div></th>
                    <th class="rotate-75"><div><span>Postmasters</span></div></th>
                    <th class="rotate-75"><div><span>Domain Aliases</span></div></th>
                  {% endif %}
                  <th class="rotate-75"><div><span>Enabled</span></div></th>
                  <th class="rotate-75"><div><span>Edit</span></div></th>
                  <th class="rotate-75"><div><span>Delete</span></div></th>
                </tr>
              </thead>
              <tbody>
              
              {% for domain in domainlist %}
                <tr{% if not domain.enabled %} class="disabled"{% endif %}>
                  <td title="{{ domain.comment }}"> <a id="{{ domain.domain_id }}" class="anchor-top""></a>{{ domain.domainname }}</td>
                  {% if domaintype=='alias' %}
                    <td>{{ domain.domains }}</td>
                  {% endif %}
                  {% if domaintype=='local' %}
                        <td>{{ domain.relayto }}</td>
                        <td style="text-align:right;">
                        {% if domain.localusers %}
                            <a href="{{ url_for('accounts.accountlist', domainid=domain.domain_id, accounttype='local') }}">
                                {{ domain.localusers.count() }}
                                <i class="far fa-list-alt"></i>
                            </a>
                        {% else %}
                            0
                        {% endif %}
                        <a href="{{ url_for('accounts.account_add', domainid=domain.domain_id, accounttype='local') }}">
                                <i class="fas fa-user-plus"></i>
                        </a>
                      </td>
                      <td style="text-align:right;">
                        {% if domain.aliasusers %}
                            <a href="{{ url_for('accounts.accountlist', domainid=domain.domain_id, accounttype='alias') }}">
                                {{ domain.aliasusers.count() }}
                                <i class="far fa-list-alt"></i>
                            </a>
                        {% else %}
                            0
                        {% endif %}
                        <a href="{{ url_for('accounts.account_add', domainid=domain.domain_id, accounttype='alias') }}">
                                <i class="fas fa-user-plus"></i>
                        </a>
                      </td>
                      <td style="text-align:right;">
                        {% if domain.postmasters %}
                            {{ domain.postmasters.count() }}
                        {% else %}
                            0
                        {% endif %}
                      </td>
                      <td style="text-align:right;">
                        {% if domain.aliases %}
                            {{ domain.aliases.count() }}
                        {% else %}
                            0
                        {% endif %}
                      </td>
                  {% endif %}
                  <td style="text-align:center;">
                    {% if domaintype=='alias' or domain.id>1 %}
                        <a href="{{ url_for('domains.domains_enabled', domainid=domain.id, domaintype=domaintype) }}">
                        {% if domain.enabled %}
                            <i class="fa fa-toggle-on"></i> 
                        {% else %}
                            <i class="fa fa-toggle-off"></i> 
                        {% endif %}
                        </a>
                    {% else %}
                        <i class="fa fa-toggle-on"></i>
                    {% endif %}
                  </td>
                  <td style="text-align:center;">
                    <a href="{{ url_for('domains.domains_edit', domainid=domain.id, domaintype=domaintype) }}">
                        <i class="far fa-edit"></i>
                    </a>
                  </td>
                  <td style="text-align:center;">
                    {% if domain.is_deleteable %}
                        <a href="{{ url_for('domains.domains_delete', domainid=domain.id, domaintype=domaintype) }}">
                            <i class="far fa-trash-alt"></i> 
                        </a>
                    {% else %}
                        <i class="far fa-trash-alt small disabled" data-toggle="tooltip" title="You can not delete an enabled domain or a domain having accounts or aliases"></i>
                    {% endif %}
                  </td>
                </tr>
              {% endfor %}
              
              </tbody>
            </table>
          </div>
        {% else %}
          <div style="text-align: center">
              <h3> No domains have been added. </h3>
              <hr class="intro-divider">
            <a href="{{ url_for('domains.domains_add', domaintype=domaintype) }}" class="btn btn-default">
              <i class="fa fa-plus"></i>
              Add Domain
            </a>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}