app/accounts/__init__.py
# app/accounts/__init__.py
# This file is part of veximpy

from flask import Blueprint

accounts = Blueprint('accounts', __name__, template_folder='templates/accounts')

from . import views

app/accounts/views.py
# app/accounts/views.py
# This file is part of veximpy

import logging
#from sqlalchemy.sql import or_, and_, tuple_
from flask import flash, redirect, render_template, request, url_for
from flask_login import login_required
from sqlalchemy.orm.exc import NoResultFound
from markupsafe import Markup
from .forms import AccountFormLocal, AccountFormAlias, AccountFormFail, AccountFormCatchall #, AccountFormMailinglist
from . import accounts
from ..models.models import Domain, User
from app.app import db
from ..config.settings import settings, accountlist_title
from ..lib.decorators import accountid_check, accounttyp_required, domainid_check, postmaster_required, user_required

#from ..back import back

@accounts.route('/accountlist/<int:domainid>/<accounttype>/')
@accounts.route('/accountlist/<int:domainid>/',  defaults={'accounttype': 'local'})
@accounts.route('/accountlist/',  defaults={'domainid': 0, 'accounttype': 'local'})
@login_required
@postmaster_required
@accounttyp_required
@domainid_check
def accountlist(domainid, accounttype):
    """
    Render the domainlist template on the / route
    """

    if accounttype == 'local':
        accounttype_list = ['local', 'piped']
    elif accounttype =='catch':
        return redirect(url_for('accounts.account_add', domainid=domainid, accounttype=accounttype))
    else:
        accounttype_list = [accounttype]

    domain = Domain.query.get_or_404(domainid)

    accountlist = (User.query.filter_by(domain_id=domainid)
                             .filter(User.type.in_(accounttype_list)).order_by(User.localpart))

    return render_template('accounts/accountlist.html',
        domainid=domainid,
        title="Accounts", list_title=accountlist_title[accounttype] + " accounts for " + domain.domain,
        postmasterdeleteallow=settings['POSTMASTER_DELETEALLOW'],
        accountlist=accountlist,
        accounttype=accounttype,
        domainname=domain.domain)

@accounts.route('/account_enabled/<int:accountid>/<accounttype>', methods=['GET', 'POST'])
@accounts.route('/account_enabled/',  defaults={'accountid': 0, 'accounttype': 'local'}, methods=['GET', 'POST'])
@login_required
@postmaster_required
@accountid_check
def account_enabled(accountid, accounttype):
    """
    Render the homepage template on the / route
    """

    try:
        account = User.query.filter(User.user_id == accountid).one()
    except NoResultFound:
        flash(Markup('We couldn\'t find the accountid <b>' + str(accountid) + '</b>.'), 'error')
        return redirect(url_for('accounts.accountlist', domainid=account.domain_id, accounttype=accounttype))

    if account.enabled == 0 or account.user_id == 1:
       account.enabled = 1
       enabledtxt = 'enabled'
       flashtype = 'success'
    else:
        account.enabled = 0
        enabledtxt = 'disabled'
        flashtype = 'warning'

    db.session.commit()
    flash(Markup('You have successfully ' + enabledtxt +' the account <b>' + account.username + '</b>.'), flashtype)

    return redirect(url_for('accounts.accountlist', _anchor=accountid, domainid=account.domain_id, accounttype=accounttype))


@accounts.route('/account_add/<int:domainid>/<accounttype>', methods=['GET', 'POST'])
@accounts.route('/account_add/<int:domainid>', defaults={'accounttype': 'local'}, methods=['GET', 'POST'])
@login_required
@postmaster_required
@accounttyp_required
def account_add(domainid, accounttype):
    """
    Render the homepage template on the / route
    """

    add_account = True
    accountname = None

    try:
        domain = Domain.query.filter(Domain.domain_id == domainid).one()
    except NoResultFound:
        flash(Markup('We couldn\'t find the domainid <b>' + str(domainid) + '</b>.'), 'error')

    account = User(**domain.get_accountdefaults_dict())
 
    if accounttype in ['local', 'piped']:
        form = AccountFormLocal(obj=account, action='add', domain=domain)
    elif accounttype == 'alias':
        account.smtp = ''
        form = AccountFormAlias(obj=account, action='add', domain=domain)
    elif accounttype == 'fail':
        form = AccountFormFail(obj=account, action='add', domain=domain)
    elif accounttype == 'catch':
        try:
            account = User.query.filter(User.username == '*@' + domain.domain).one()
            return redirect(url_for('accounts.account_edit', accountid=account.user_id, accounttype=accounttype))
        except:
            pass
        account.localpart = '*'
        account.username = '*@' + domain.domain
        account.smtp = ''
        accountname = account.username
        form = AccountFormCatchall(obj=account, action='add', domain=domain)

    #elif accounttype == 'list':
    #     form = AccountFormMailinglist(obj=account, action='add', domain=domain)

    #if request.method == 'GET':
        #form.process(MultiDict(domaindefaults))
    if not accountname:
         accountname = form.username.data

    if request.method == 'POST':
        if form.submitcancel.data:
            return redirect(url_for('accounts.accountlist', domainid=account.domain_id, accounttype=accounttype))

        if form.account_save(account):
            try:
                db.session.add(account)
                db.session.commit()
            except:
                db.session.rollback()
                flash(Markup('Account <b>' + accountname + '</b> already exists.'), 'error')
                return render_template('accounts/account.html', action='Add',
                                    accountname = '', 
                                    add_account=add_account, form=form,
                                    domainname=domain.domain,
                                    domainid=domainid,
                                    title='Add ' + accounttype + ' account')
        else:
            flash(Markup('An error occured on adding account <b>' + accountname + '</b> during form data validation.'), 'error')
            return render_template('accounts/account.html', action='Add',
                                    accountname = '', 
                                    add_account=add_account, form=form,
                                    domainname=domain.domain,
                                    domainid=domainid,
                                    title='Add ' + accounttype + ' account')
        flash(Markup('You have successfully added the account <b>' + accountname + '</b>'), 'success')
        return redirect(url_for('accounts.accountlist', domainid=account.domain_id, accounttype=accounttype))

    return render_template('accounts/account.html', action='Add',
                            add_account=add_account, form=form,
                            accountname=accountname,
                            domainname=domain.domain, 
                            domainid=domainid,
                            title='Add ' + accounttype + ' account')


@accounts.route('/account_edit/<int:accountid>/<accounttype>', methods=['GET', 'POST'])
@accounts.route('/account_edit/',  defaults={'accountid': 0, 'accounttype': 'local'}, methods=['GET', 'POST'])
#@user_required
@login_required
@accounttyp_required
def account_edit(accountid, accounttype):
    """
    Render the homepage template on the / route
    """

    add_account = False

    try:
        account = User.query.filter_by(user_id=accountid).one()
        domain = Domain.query.filter_by(domain_id=account.domain_id).one()

        if accounttype  in ['local', 'piped']:
            form = AccountFormLocal(obj=account, action='edit',  domain=domain)
        elif accounttype == 'alias':
            form = AccountFormAlias(obj=account, action='edit', domain=domain)
        elif accounttype == 'fail':
            form = AccountFormFail(obj=account, action='edit', domain=domain)
        elif accounttype == 'catch':
            form = AccountFormCatchall(obj=account, action='edit', domain=domain)
        accountname = account.username
    except NoResultFound:
        flash(Markup('We couldn\'t find the accountid <b>' + str(accountid) + '</b>.'), 'error')
        if accounttype == 'catch': accounttype='local'
        return redirect(url_for('accounts.accountlist', domainid=account.domain_id, _anchor=accountid, accounttype=accounttype))

    if form.submitcancel.data:
        if accounttype == 'catch': accounttype='local'
        return redirect(url_for('accounts.accountlist', domainid=account.domain_id, _anchor=accountid, accounttype=accounttype))

    if request.method == 'POST':
        if form.account_save(account):
            try:
                logging.debug(account.__dict__)
                db.session.commit()
                flash(Markup('You have successfully edited the domain <b>' + accountname + '</b>'), 'success')
                # redirect to accountlist page
                if accounttype == 'catch': accounttype='local'
                return redirect(url_for('accounts.accountlist', domainid=account.domain_id, _anchor=accountid, accounttype=accounttype))
            except:
                db.session.rollback()
                flash(Markup('<b>' + accountname + '</b> name already exists.'), 'error')
                return render_template('domains/domain.html', action='Edit',
                                accountname = accountname, 
                                add_account=add_account, form=form,
                                title='Edit ' + accounttype + 'account')
        else:
            # populate form with readonly data again
            form.localpart.data = account.localpart
            flash(Markup('An error occured on editing account <b>' + accountname + '</b> during form data validation.'), 'error')

    return render_template('accounts/account.html', action='Edit',
                            add_account=add_account, form=form,
                            accountname=accountname,
                            domainname=domain.domain,
                            domainid=account.domain_id, 

app/templates/accounts/account.html
<!-- app/templates/accounts/account.html -->
<!-- This file is part of veximpy -->

{% import "bootstrap/wtf.html" as wtf %}
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}
    {% if add_account %}
        Add Account
    {% else %}
        Edit Account
    {% endif %}
{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center">
            {% if add_account %}
                <h1>{{ title }}</h1>
            {% else %}
                <h1>{{ title }} <b>{{ accountname }}</b></h1>
            {% endif %}
            <br/>
            {{ wtf.quick_form(form) }}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/accounts/accountlist.html
<!-- app/templates/accounts/accountlist.html -->
<!-- This file is part of veximpy -->

{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Domains{% endblock %}
{% block body %}
<script class="init" type="text/javascript">
    $(document).ready(function() {
         $('#localtable').DataTable( {
              "dom": 'Blfrtip',
              "buttons": [ 'copy', 'excel', 'pdf' ],
              "columnDefs": [ { "orderable": false, "targets": [ 8, 9, 10 ] } ]
         } );
         $('#aliastable').DataTable( {
              "columnDefs": [
                  { "orderable": false, "targets": [ 4, 5, 6 ] }
              ]
         } );
    } );
</script>
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <h1 style="text-align:center;">{{ list_title }}</h1>
        {% if accountlist %}
          <hr class="intro-divider">
          <div class="postition-absolute" style="text-align: center">
            <a href="{{ url_for('accounts.account_add', domainid=domainid, accounttype=accounttype) }}" class="btn btn-default">
              <i class="fa fa-plus"></i>
              Add Account
            </a>
          </div>
          <div class="center table-responsive-sm">
            <table id="{{ accounttype }}table" class="table table-sm table-striped table-bordered table-hover rotate-75 display">
                <caption>List of accounts</caption>
                <colgroup>
                    <col span="1" style="width: *;">
                    <col span="1" style="width: *;">
                    <col span="1" style="width: *;">
                    
                    {% if accounttype=='local' %}
                      <col span="1" style="width: 60px;">
                      <col span="1" style="width: 35px;">
                      <col span="1" style="width: 35px;">
                      <col span="1" style="width: 35px;">
                      <col span="1" style="width: 35px;">
                    {% endif %}
                    {% if accounttype=='alias' %}
                      <col span="1" style="width: 35px;">
                    {% endif %}
                    <col span="1" style="width: 35px;">
                    <col span="1" style="width: 35px;">
                    <col span="1" style="width: 35px;">
                </colgroup>
              <thead>
                <tr class="rotate-75">
                  <th class="rotate-75"><div><span>Name</span></div></th>
                  <th class="rotate-75"><div><span>Username</span></div></th>
                  <th class="rotate-75"><div><span>Localpart</span></div></th>
                  <!-- <th width="30%"> Maildir </th> -->
                  {% if accounttype=='local' %}
                    <th class="rotate-75"><div><span>Quota [MB]</span></div></th>
                    <th class="rotate-75"><div><span>Piped</span></div></th>
                    <th class="rotate-75"><div><span>Forwarded</span></div></th>
                    <th class="rotate-75"><div><span>Siteadmin</span></div></th>
                    <th class="rotate-75"><div><span>Postmaster</span></div></th>
                  {% endif %}
                  {% if accounttype=='alias' %}
                    <th class="rotate-75"><div><span>Login</span></div></th>
                  {% endif %}
                  <th class="rotate-75"><div><span>Enabled</span></div></th>
                  <th class="rotate-75"><div><span>Edit</span></div></th>
                  <th class="rotate-75"><div><span>Delete</span></div></th>
                </tr>
              </thead>
              <tbody>
              
              {% for account in accountlist %}
                <tr title="{{ account.comment }}">
                  <td title="{{ account.comment }}"> <a id="{{ account.user_id }}" class="anchor-top"></a>{{ account.realname }}</td>
                  <td> {{ account.username }} </td>
                  <td> {{ account.localpart }} </td>
                  
                  {% if accounttype=='local' %}
                  <td class="small" style="text-align:right;"> {{ account.quota }} </td>
                    <td style="text-align:center;">
                        {% if account.is_piped %}
                            <i class="far fa-check-circle"></i>
                        {% endif %}
                      </td>
                    <td style="text-align:center;">
                        {% if account.on_forward %}
                            <i class="far fa-check-circle"></i>
                        {% endif %}
                      </td>
                      <td style="text-align:center;">
                        {% if account.is_siteadmin %}
                            <i class="far fa-check-circle"></i>
                        {% endif %}
                      </td>
                      <td style="text-align:center;">
                        {% if account.is_postmaster %}
                            <i class="far fa-check-circle"></i>
                        {% endif %}
                      </td>
                  {% endif %}
                  {% if accounttype=='alias' %}
                      <td style="text-align:center;">
                        {% if account.has_password %}
                            <i class="far fa-check-circle"></i>
                        {% endif %}
                      </td>
                  {% endif %}
                  <td style="text-align:center;" title="You can not disable a postmaster/siteadmin account">
                    {% if not (account.is_postmaster or account.is_siteadmin) %}
                        <a href="{{ url_for('accounts.account_enabled', accountid=account.id, accounttype=accounttype) }}">
                        {% if account.enabled %}
                          <i class="fa fa-toggle-on"></i> 
                        {% else %}
                          <i class="fa fa-toggle-off"></i> 
                        {% endif %}
                        </a>
                    {% else %}
                        {% if account.enabled %}
                          <i class="fa fa-toggle-on disabled"></i> 
                        {% else %}
                          <i class="fa fa-toggle-off disabled"></i> 
                        {% endif %}
                    {% endif %}
                  </td>
                  <td style="text-align:center;">
                    <a href="{{ url_for('accounts.account_edit', accountid=account.id, accounttype=accounttype) }}">
                        <i class="far fa-edit"></i>
                    </a>
                  </td>
                  <td style="text-align:center;" title="You can not delete an enabled account or a postmaster/siteadmin account">
                    {% if account.is_deleteable %}
                        <a href="{{ url_for('accounts.account_delete', accountid=account.id, accounttype=accounttype) }}">
                            <i class="far fa-trash-alt"></i> 
                        </a>
                    {% else %}
                        <i class="far fa-trash-alt disabled"></i>
                    {% endif %}
                  </td>
                </tr>
              {% endfor %}
              
              </tbody>
            </table>
          </div>
        {% else %}
          <div style="text-align: center">
              <h3> No accounts have been added. </h3>
              <hr class="intro-divider">
            <a href="{{ url_for('accounts.account_add', domainid=domainid, accounttype=accounttype) }}" class="btn btn-default">
              <i class="fa fa-plus"></i>
              Add Account
            </a>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}